version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - lamp-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: judging_system
      MYSQL_USER: okelo
      MYSQL_PASSWORD: kothbiro
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint.sh mysqld --innodb-use-native-aio=0 --disable-log-bin --performance_schema=0/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - lamp-network


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: okelo
      PMA_PASSWORD: kothbiro
    networks:
      - lamp-network

volumes:
  mysql_data:
    driver: local

networks:
  lamp-network:
    driver: bridge